import { jsx } from "react/jsx-runtime";
import { createContext, useState, useEffect, useContext } from "react";
import { createInertiaApp } from "@inertiajs/react";
import createServer from "@inertiajs/react/server";
import { renderToString } from "react-dom/server";
async function resolvePageComponent(path, pages) {
  for (const p of Array.isArray(path) ? path : [path]) {
    const page = pages[p];
    if (typeof page === "undefined") {
      continue;
    }
    return typeof page === "function" ? page() : page;
  }
  throw new Error(`Page not found: ${path}`);
}
const translations = {
  id: {
    nav: {
      home: "Beranda",
      studies: "Kajian",
      topics: "Topik",
      dashboard: "Dashboard",
      profile: "Profil",
      logout: "Logout"
    },
    role: {
      user: "Peneliti",
      reviewer: "Reviewer",
      director: "Direktur",
      admin: "Administrator",
      default: "Pengguna"
    },
    home: {
      eyebrow: "Knowledge Platform · Big Data BPS",
      heroTitle: "Eksplorasi Big Data",
      heroTitleHighlight: "untuk statistik resmi.",
      heroDescription: "Temukan kajian, metode, dan insight berbasis data yang mendukung pengembangan statistik resmi dan pemanfaatan Big Data.",
      exploreStudies: "Jelajahi Kajian",
      popularStudy: "KAJIAN TERPOPULER",
      previousStudy: "Kajian sebelumnya",
      nextStudy: "Kajian berikutnya",
      study: "Kajian",
      explore: "Explore",
      latestStudies: "Kajian Terbaru",
      seeAll: "Lihat semua",
      exploreByTopic: "Explore by Topic",
      focusStudies: "Fokus Kajian",
      focusDescription: "Jelajahi kajian berdasarkan topik dan bidang pemanfaatan Big Data.",
      bigDataBps: "Big Data BPS",
      dataNotOnly: "Data bukan hanya",
      numbers: "angka.",
      statement: "Kajian Big Data menjadi ruang untuk mengeksplorasi sumber data alternatif, metode baru, serta insight yang dapat mendukung penyelenggaraan statistik resmi.",
      knowledgeCenter: "Knowledge Center",
      findRelevant: "Temukan kajian yang relevan",
      withYourNeeds: "dengan kebutuhanmu.",
      ctaDescription: "Jelajahi berbagai kajian Big Data, metode, dan insight yang telah dipublikasikan.",
      exploreAllStudies: "Jelajahi Semua Kajian"
    },
    studyCard: {
      study: "KAJIAN",
      bigData: "BIG DATA",
      statistics: "BADAN PUSAT STATISTIK",
      defaultCategory: "Kajian",
      published: "Published",
      readStudy: "Baca Kajian"
    },
    common: {
      save: "Simpan",
      saveChanges: "Simpan Perubahan",
      saving: "Menyimpan...",
      cancel: "Batal",
      close: "Tutup",
      delete: "Hapus",
      edit: "Edit",
      add: "Tambah",
      search: "Cari",
      filter: "Filter",
      reset: "Reset",
      submit: "Kirim",
      loading: "Memuat...",
      back: "Kembali",
      next: "Berikutnya",
      previous: "Sebelumnya",
      yes: "Ya",
      no: "Tidak",
      confirm: "Konfirmasi",
      success: "Berhasil",
      error: "Terjadi Kesalahan",
      warning: "Perhatian",
      info: "Informasi",
      view: "Lihat",
      all: "Semua",
      status: "Status",
      category: "Kategori",
      date: "Tanggal",
      action: "Aksi",
      description: "Deskripsi",
      name: "Nama",
      email: "Email",
      password: "Password",
      reason: "Alasan",
      notes: "Catatan",
      closeMenu: "Tutup menu",
      openMenu: "Buka menu",
      fullName: "Nama lengkap",
      enterPassword: "Masukkan password",
      repeatPassword: "Ulangi password",
      newPasswordPlaceholder: "Masukkan password baru",
      repeatNewPassword: "Ulangi password baru",
      confirmPasswordPlaceholder: "Konfirmasi dengan password",
      closePreview: "Tutup preview",
      seeMore: "Lihat Selengkapnya",
      imageDescription: "Deskripsi Gambar",
      accessibilitySeoDescription: "Digunakan untuk aksesibilitas dan SEO."
    },
    footer: {
      organization: "Badan Pusat Statistik",
      studies: "Kajian",
      topics: "Topik",
      login: "Masuk",
      register: "Daftar"
    },
    sidebar: {
      dashboard: "Dashboard",
      analytics: "Analytics",
      submitStudy: "Ajukan Kajian",
      underReview: "Sedang Direview",
      users: "Pengguna",
      categories: "Kategori",
      manageStudies: "Kelola Kajian",
      researcher: "Peneliti",
      reviewer: "Reviewer",
      director: "Direktur",
      administrator: "Administrator",
      portal: "Portal Kajian",
      profile: "Profil",
      closeMenu: "Tutup menu",
      logout: "Logout"
    },
    auth: {
      login: "Masuk",
      register: "Daftar",
      forgotPassword: "Lupa Password",
      resetPassword: "Reset Password",
      confirmPassword: "Konfirmasi Password",
      verifyEmail: "Verifikasi Email",
      email: "Email",
      password: "Password",
      rememberMe: "Ingat saya",
      loginButton: "Masuk",
      registerButton: "Daftar",
      sendResetLink: "Kirim Link Reset Password",
      newPassword: "Password Baru",
      confirmNewPassword: "Konfirmasi Password Baru",
      verificationMessage: "Silakan verifikasi alamat email kamu sebelum melanjutkan.",
      resendVerification: "Kirim Ulang Email Verifikasi",
      passwordPlaceholder: "Masukkan password",
      fullNamePlaceholder: "Nama lengkap",
      confirmPasswordPlaceholder: "Ulangi password",
      newPasswordPlaceholder: "Masukkan password baru",
      repeatNewPasswordPlaceholder: "Ulangi password baru",
      confirmPasswordPlaceholder: "Konfirmasi dengan password"
    },
    studies: {
      title: "Kajian",
      searchPlaceholder: "Cari judul atau ringkasan kajian...",
      activeFilter: "Filter aktif",
      allCategories: "Semua kategori",
      noStudies: "Kajian tidak ditemukan",
      resetFilter: "Reset Filter",
      readMore: "Baca Kajian",
      latest: "Kajian Terbaru",
      popular: "Kajian Terpopuler"
    },
    studyDetail: {
      backToStudies: "Kembali ke Kajian",
      summary: "Ringkasan Kajian",
      keywords: "Kata Kunci",
      discussion: "Diskusi",
      noComments: "Belum ada komentar",
      firstComment: "Jadilah orang pertama yang memberikan komentar.",
      writeComment: "Tulis komentar...",
      sendComment: "Kirim Komentar",
      copyLink: "Salin Link",
      share: "Bagikan",
      relevantStudies: "Kajian yang Relevan",
      previous: "Sebelumnya",
      next: "Berikutnya",
      readStudy: "Baca Kajian",
      commentPlaceholder: "Tulis komentar atau tanggapanmu...",
      commentPlaceholder: "Tulis komentar atau tanggapanmu..."
    },
    dashboard: {
      dashboard: "Dashboard",
      overview: "Overview",
      analytics: "Analytics",
      performance: "Performance",
      studies: "Kajian",
      users: "Pengguna",
      categories: "Kategori",
      submitStudy: "Ajukan Kajian",
      underReview: "Sedang Direview",
      published: "Published",
      draft: "Draft",
      submitted: "Submitted",
      revision: "Revision",
      rejected: "Rejected",
      directorReview: "Review Direktur",
      views: "Views",
      likes: "Likes",
      comments: "Comments",
      shares: "Shares"
    },
    user: {
      dashboard: "Dashboard",
      myStudies: "Kajian Saya",
      submitStudy: "Ajukan Kajian",
      editStudy: "Edit Kajian",
      createStudy: "Ajukan Kajian",
      studyTitle: "Judul Kajian",
      category: "Kategori",
      keywords: "Kata Kunci",
      summary: "Ringkasan Kajian",
      content: "Isi Kajian",
      cover: "Cover",
      approvalFlow: "Alur Persetujuan",
      reviewerOnly: "Reviewer saja",
      reviewerDirector: "Reviewer + Direktur",
      saveDraft: "Simpan sebagai Draft",
      revisionRequired: "Kajian memerlukan revisi.",
      deleteStudy: "Hapus Kajian",
      deleteRequest: "Ajukan Penghapusan",
      deletionReason: "Jelaskan alasan penghapusan kajian...",
      maxKeywords: "Maksimal 7 kata kunci.",
      typeKeyword: "Ketik kata kunci lalu tekan Enter...",
      studyPlaceholder: "Masukkan judul kajian...",
      summaryPlaceholder: "Jelaskan secara singkat isi kajian...",
      editorPlaceholder: "Mulai menulis kajian... Ketik / untuk menambahkan blok.",
      submitForReview: "Ajukan untuk Review",
      sending: "Mengirim...",
      deleteReasonPlaceholder: "Jelaskan alasan penghapusan kajian...",
      noStudyContent: "Belum ada isi kajian.",
      summaryPlaceholder: "Jelaskan secara singkat isi kajian...",
      calloutPlaceholder: "Tulis informasi yang ingin ditonjolkan...",
      imageDescriptionPlaceholder: "Jelaskan isi gambar...",
      totalStudies: "TOTAL KAJIAN",
      allMyStudies: "Semua kajian saya",
      publishedStudies: "Sudah diterbitkan",
      totalViews: "TOTAL VIEWS",
      allStudies: "Seluruh kajian",
      totalLikes: "Total suka",
      totalComments: "Total komentar",
      totalShares: "Total dibagikan",
      deleteReasonPlaceholder: "Jelaskan alasan penghapusan kajian...",
      noStudyContent: "Belum ada isi kajian.",
      summaryPlaceholder: "Jelaskan secara singkat isi kajian...",
      calloutPlaceholder: "Tulis informasi yang ingin ditonjolkan...",
      imageDescriptionPlaceholder: "Jelaskan isi gambar...",
      publishedLabel: "PUBLISHED",
      likesLabel: "LIKES",
      commentsLabel: "COMMENTS",
      sharesLabel: "SHARES"
    },
    reviewer: {
      dashboard: "Dashboard Reviewer",
      activeStudies: "Kajian yang Sedang Ditangani",
      currentReviews: "Current Reviews",
      incomingStudies: "Kajian Menunggu Review",
      underReview: "Sedang Direview",
      waitingReview: "Menunggu Review",
      revisionRequired: "Menunggu perbaikan",
      startReview: "Mulai Review",
      continueReview: "Lanjut Review",
      manageReviews: "Kelola Review Kajian",
      reviewStudy: "Review Kajian",
      noActiveStudies: "Tidak ada kajian yang sedang direview.",
      noIncomingStudies: "Tidak ada kajian yang menunggu review.",
      studyBeingHandled: "Kajian yang sedang kamu tangani untuk proses review.",
      newStudies: "Kajian baru masuk",
      studiesYouReview: "Kajian yang sedang kamu review",
      approve: "Setujui",
      requestRevision: "Minta Revisi",
      reject: "Tolak",
      approvalFlow: "Alur Persetujuan",
      reviewerOnly: "Reviewer saja",
      reviewerDirector: "Reviewer + Direktur",
      notePlaceholder: "Tulis catatan reviewer...",
      notePlaceholder: "Tulis catatan reviewer..."
    },
    director: {
      dashboard: "Dashboard Direktur",
      review: "Review Kajian",
      reviewStudies: "Kajian Menunggu Review",
      incomingStudies: "Kajian Masuk",
      directorReview: "Review Direktur",
      waitingReview: "Menunggu Review",
      revisionRequired: "Menunggu perbaikan",
      startReview: "Mulai Review",
      continueReview: "Lanjut Review",
      manageReviews: "Kelola Review Kajian",
      noStudies: "Tidak ada kajian yang menunggu review.",
      approve: "Setujui & Terbitkan",
      requestRevision: "Minta Revisi",
      reject: "Tolak",
      notePlaceholder: "Tulis catatan Direktur...",
      notePlaceholder: "Tulis catatan Direktur..."
    },
    admin: {
      dashboard: "Dashboard Admin",
      management: "Management Platform",
      overview: "Overview",
      performance: "Performance",
      analytics: "Analytics",
      platformActivity: "Aktivitas Platform",
      studies: "Kajian",
      studyManagement: "Kelola Kajian",
      allStudies: "Semua Kajian",
      manageStudies: "Pantau seluruh kajian dan kelola permintaan penghapusan dari peneliti.",
      noStudies: "Belum ada kajian.",
      studyNotFound: "Kajian tidak ditemukan.",
      viewStudy: "Lihat Kajian",
      users: "Pengguna",
      userManagement: "Kelola Pengguna",
      manageUsers: "Kelola akun peneliti, reviewer, direktur, dan administrator.",
      noUsers: "Belum ada pengguna.",
      categories: "Kategori",
      categoryManagement: "Kelola Kategori",
      manageCategories: "Kelola kategori yang digunakan untuk mengelompokkan kajian.",
      noCategories: "Belum ada kategori.",
      deletionRequest: "Permintaan Penghapusan",
      deletionRequests: "Permintaan Penghapusan",
      pendingDeletion: "Permintaan penghapusan yang menunggu.",
      approveDeletion: "Setujui & Hapus",
      rejectDeletion: "Tolak Permintaan",
      rejectRequest: "Tolak Request",
      rejectionReason: "Jelaskan alasan Admin menolak permintaan penghapusan ini.",
      confirmDeletion: "Setujui Penghapusan?",
      deleteConfirmation: "Apakah kamu yakin ingin menghapus kajian ini?",
      published: "Published",
      underReview: "Under Review",
      waitingReviewer: "Menunggu reviewer",
      directorReview: "Review Direktur",
      totalUsers: "Total Pengguna",
      totalStudies: "Total Kajian",
      totalViews: "Total Views",
      totalLikes: "Total Likes",
      totalComments: "Total Comments",
      totalShares: "Total Shares",
      uniqueVisitors: "Unique Visitors",
      studyViews: "Views kajian",
      traffic: "Traffic",
      categoryDistribution: "Distribusi Kategori",
      workflowDistribution: "Distribusi Workflow",
      popularStudies: "Kajian Terpopuler",
      recentActivity: "Aktivitas 7 hari terakhir",
      engagement: "Berdasarkan engagement",
      categoryNamePlaceholder: "Contoh: Web Scraping",
      categoryDescriptionPlaceholder: "Deskripsi singkat kategori",
      searchStudyPlaceholder: "Cari judul kajian...",
      rejectionReasonPlaceholder: "Tulis alasan penolakan...",
      searchUserPlaceholder: "Cari nama atau email...",
      passwordMinimum: "Minimal 8 karakter",
      waitingReview: "Menunggu Review"
    },
    editor: {
      primary: "PRIMARY",
      embed: "EMBED",
      text: "Teks",
      textDescription: "Tulis paragraf biasa",
      heading: "Heading",
      headingDescription: "Judul bagian utama",
      subheading: "Subheading",
      subheadingDescription: "Subjudul bagian",
      image: "Gambar",
      imageDescription: "Upload atau tambahkan gambar",
      gallery: "Gallery",
      galleryDescription: "Buat galeri beberapa gambar",
      divider: "Divider",
      dividerDescription: "Tambahkan garis pemisah",
      quote: "Quote",
      quoteDescription: "Tambahkan kutipan",
      callout: "Callout",
      calloutDescription: "Kotak informasi yang menonjol",
      video: "Video",
      videoDescription: "Tambahkan video dari URL",
      pdf: "File / PDF",
      pdfDescription: "Upload dokumen PDF",
      button: "Button",
      buttonDescription: "Tambahkan tombol tautan",
      code: "Code",
      codeDescription: "Tambahkan blok kode",
      youtube: "YouTube",
      youtubeDescription: "Embed video YouTube",
      github: "GitHub",
      githubDescription: "Tampilkan repository GitHub",
      gitlab: "GitLab",
      gitlabDescription: "Tampilkan repository GitLab",
      vimeo: "Vimeo",
      vimeoDescription: "Embed video Vimeo",
      embed: "Embed",
      embedDescription: "Masukkan URL embed",
      titlePlaceholder: "Masukkan judul kajian...",
      keywordPlaceholder: "Ketik kata kunci lalu tekan Enter...",
      summaryPlaceholder: "Jelaskan secara singkat isi kajian...",
      contentPlaceholder: "Mulai menulis kajian... Ketik / untuk menambahkan blok.",
      maxKeywords: "Maksimal 7 kata kunci.",
      maxGallery: "Gallery maksimal 8 gambar.",
      maxImageSize: "Setiap gambar maksimal 4 MB.",
      maxPdfSize: "Ukuran PDF maksimal 10 MB.",
      selectedPdf: "Dokumen PDF",
      openFull: "Buka penuh",
      studyVideo: "Video kajian",
      previewCover: "Preview cover",
      addCallout: "Tambahkan Callout",
      addVideo: "Tambahkan Video",
      addButton: "Tambahkan Button",
      addBlock: "Tambahkan Blok",
      uploadPdfOnly: "File yang dipilih harus berupa PDF.",
      uploadImageError: "Gagal mengupload gambar.",
      uploadGalleryError: "Gagal mengupload gallery.",
      embedStudy: "Embed kajian",
      calloutTitle: "Judul Callout",
      calloutContent: "Isi Callout",
      buttonText: "Teks Tombol",
      targetUrl: "URL Tujuan",
      calloutTitlePlaceholder: "Masukkan judul callout...",
      buttonTextPlaceholder: "Contoh: Lihat Selengkapnya",
      type: "Tipe",
      warning: "Peringatan",
      success: "Sukses",
      important: "Penting",
      youtubeUrl: "URL YouTube",
      vimeoUrl: "URL Vimeo",
      embedUrl: "URL Embed",
      videoUrl: "URL Video",
      githubRepositoryUrl: "URL Repository GitHub",
      gitlabRepositoryUrl: "URL Repository GitLab",
      enterGithubRepository: "Masukkan URL repository GitHub.",
      enterGitlabRepository: "Masukkan URL repository GitLab.",
      enterEmbedUrl: "Masukkan URL yang ingin di-embed ke dalam kajian.",
      calloutPlaceholder: "Tulis informasi yang ingin ditonjolkan...",
      closePreview: "Tutup preview",
      imageDescriptionPlaceholder: "Deskripsikan gambar...",
      noContent: "Belum ada konten kajian.",
      seeMore: "Lihat Selengkapnya",
      editor: "EDITOR",
      preview: "Preview",
      typeCommand: "Ketik / untuk command",
      urlRequired: "URL tidak boleh kosong.",
      imageSizeError: "Ukuran gambar maksimal 4 MB.",
      imageUploadError: "Gagal mengupload gambar.",
      imageUploadFailed: "Gambar gagal diupload.",
      galleryMax: "Gallery maksimal 8 gambar.",
      galleryImageMaxSize: "Setiap gambar maksimal 4 MB.",
      galleryUploadError: "Gagal mengupload gallery.",
      galleryUploadFailed: "Gallery gagal diupload."
    },
    modal: {
      confirmation: "Konfirmasi",
      continue: "Ya, Lanjutkan",
      cancel: "Batal",
      close: "Tutup",
      inputInformation: "Masukkan Informasi",
      input: "Input",
      save: "Simpan"
    },
    toast: {
      success: "Berhasil",
      error: "Terjadi Kesalahan",
      warning: "Perhatian",
      close: "Tutup"
    }
  },
  en: {
    nav: {
      home: "Home",
      studies: "Studies",
      topics: "Topics",
      dashboard: "Dashboard",
      profile: "Profile",
      logout: "Logout"
    },
    role: {
      user: "Researcher",
      reviewer: "Reviewer",
      director: "Director",
      admin: "Administrator",
      default: "User"
    },
    home: {
      eyebrow: "Knowledge Platform · Big Data BPS",
      heroTitle: "Explore Big Data",
      heroTitleHighlight: "for official statistics.",
      heroDescription: "Discover studies, methods, and data-driven insights that support the development of official statistics and the utilization of Big Data.",
      exploreStudies: "Explore Studies",
      popularStudy: "POPULAR STUDY",
      previousStudy: "Previous study",
      nextStudy: "Next study",
      study: "Study",
      explore: "Explore",
      latestStudies: "Latest Studies",
      seeAll: "See all",
      exploreByTopic: "Explore by Topic",
      focusStudies: "Study Focus",
      focusDescription: "Explore studies based on topics and areas of Big Data utilization.",
      bigDataBps: "Big Data BPS",
      dataNotOnly: "Data is not just",
      numbers: "numbers.",
      statement: "Big Data studies provide a space to explore alternative data sources, new methods, and insights that can support the production of official statistics.",
      knowledgeCenter: "Knowledge Center",
      findRelevant: "Find studies relevant",
      withYourNeeds: "to your needs.",
      ctaDescription: "Explore various Big Data studies, methods, and published insights.",
      exploreAllStudies: "Explore All Studies"
    },
    studyCard: {
      study: "STUDY",
      bigData: "BIG DATA",
      statistics: "STATISTICS INDONESIA",
      defaultCategory: "Study",
      published: "Published",
      readStudy: "Read Study"
    },
    common: {
      save: "Save",
      saveChanges: "Save Changes",
      saving: "Saving...",
      cancel: "Cancel",
      close: "Close",
      delete: "Delete",
      edit: "Edit",
      add: "Add",
      search: "Search",
      filter: "Filter",
      reset: "Reset",
      submit: "Submit",
      loading: "Loading...",
      back: "Back",
      next: "Next",
      previous: "Previous",
      yes: "Yes",
      no: "No",
      confirm: "Confirm",
      success: "Success",
      error: "An Error Occurred",
      warning: "Warning",
      info: "Information",
      view: "View",
      all: "All",
      status: "Status",
      category: "Category",
      date: "Date",
      action: "Action",
      description: "Description",
      name: "Name",
      email: "Email",
      password: "Password",
      reason: "Reason",
      notes: "Notes",
      closeMenu: "Close menu",
      openMenu: "Open menu",
      fullName: "Full name",
      enterPassword: "Enter password",
      repeatPassword: "Repeat password",
      newPasswordPlaceholder: "Enter new password",
      repeatNewPassword: "Repeat new password",
      confirmPasswordPlaceholder: "Confirm with password",
      closePreview: "Close preview",
      seeMore: "See More",
      imageDescription: "Image Description",
      accessibilitySeoDescription: "Used for accessibility and SEO."
    },
    footer: {
      organization: "Statistics Indonesia",
      studies: "Studies",
      topics: "Topics",
      login: "Login",
      register: "Register"
    },
    sidebar: {
      dashboard: "Dashboard",
      analytics: "Analytics",
      submitStudy: "Submit Study",
      underReview: "Under Review",
      users: "Users",
      categories: "Categories",
      manageStudies: "Manage Studies",
      researcher: "Researcher",
      reviewer: "Reviewer",
      director: "Director",
      administrator: "Administrator",
      portal: "Study Portal",
      profile: "Profile",
      closeMenu: "Close menu",
      logout: "Logout"
    },
    auth: {
      login: "Login",
      register: "Register",
      forgotPassword: "Forgot Password",
      resetPassword: "Reset Password",
      confirmPassword: "Confirm Password",
      verifyEmail: "Verify Email",
      email: "Email",
      password: "Password",
      rememberMe: "Remember me",
      loginButton: "Login",
      registerButton: "Register",
      sendResetLink: "Send Password Reset Link",
      newPassword: "New Password",
      confirmNewPassword: "Confirm New Password",
      verificationMessage: "Please verify your email address before continuing.",
      resendVerification: "Resend Verification Email",
      passwordPlaceholder: "Enter password",
      fullNamePlaceholder: "Full name",
      confirmPasswordPlaceholder: "Repeat password",
      newPasswordPlaceholder: "Enter new password",
      repeatNewPasswordPlaceholder: "Repeat new password",
      confirmPasswordPlaceholder: "Konfirmasi dengan password"
    },
    studies: {
      title: "Studies",
      searchPlaceholder: "Search study titles or summaries...",
      activeFilter: "Active filters",
      allCategories: "All categories",
      noStudies: "No studies found",
      resetFilter: "Reset Filter",
      readMore: "Read Study",
      latest: "Latest Studies",
      popular: "Popular Studies"
    },
    studyDetail: {
      backToStudies: "Back to Studies",
      summary: "Study Summary",
      keywords: "Keywords",
      discussion: "Discussion",
      noComments: "No comments yet",
      firstComment: "Be the first to leave a comment.",
      writeComment: "Write a comment...",
      sendComment: "Post Comment",
      copyLink: "Copy Link",
      share: "Share",
      relevantStudies: "Relevant Studies",
      previous: "Previous",
      next: "Next",
      readStudy: "Read Study",
      commentPlaceholder: "Write your comment or response...",
      commentPlaceholder: "Write your comment or response..."
    },
    dashboard: {
      dashboard: "Dashboard",
      overview: "Overview",
      analytics: "Analytics",
      performance: "Performance",
      studies: "Studies",
      users: "Users",
      categories: "Categories",
      submitStudy: "Submit Study",
      underReview: "Under Review",
      published: "Published",
      draft: "Draft",
      submitted: "Submitted",
      revision: "Revision",
      rejected: "Rejected",
      directorReview: "Director Review",
      views: "Views",
      likes: "Likes",
      comments: "Comments",
      shares: "Shares"
    },
    user: {
      dashboard: "Dashboard",
      myStudies: "My Studies",
      submitStudy: "Submit Study",
      editStudy: "Edit Study",
      createStudy: "Submit Study",
      studyTitle: "Study Title",
      category: "Category",
      keywords: "Keywords",
      summary: "Study Summary",
      content: "Study Content",
      cover: "Cover",
      approvalFlow: "Approval Flow",
      reviewerOnly: "Reviewer only",
      reviewerDirector: "Reviewer + Director",
      saveDraft: "Save as Draft",
      revisionRequired: "This study requires revision.",
      deleteStudy: "Delete Study",
      deleteRequest: "Request Deletion",
      deletionReason: "Explain the reason for deleting the study...",
      maxKeywords: "Maximum 7 keywords.",
      typeKeyword: "Type a keyword and press Enter...",
      studyPlaceholder: "Enter study title...",
      summaryPlaceholder: "Briefly describe the study...",
      editorPlaceholder: "Start writing your study... Type / to add a block.",
      submitForReview: "Submit for Review",
      sending: "Sending...",
      deleteReasonPlaceholder: "Explain the reason for deleting this study...",
      noStudyContent: "No study content yet.",
      summaryPlaceholder: "Briefly describe the study...",
      calloutPlaceholder: "Write the information you want to highlight...",
      imageDescriptionPlaceholder: "Describe the image...",
      totalStudies: "TOTAL STUDIES",
      allMyStudies: "All my studies",
      publishedStudies: "Published",
      totalViews: "TOTAL VIEWS",
      allStudies: "All studies",
      totalLikes: "Total likes",
      totalComments: "Total comments",
      totalShares: "Total shares",
      deleteReasonPlaceholder: "Explain the reason for deleting this study...",
      noStudyContent: "No study content yet.",
      summaryPlaceholder: "Briefly describe the study...",
      calloutPlaceholder: "Write the information you want to highlight...",
      imageDescriptionPlaceholder: "Describe the image...",
      publishedLabel: "PUBLISHED",
      likesLabel: "LIKES",
      commentsLabel: "COMMENTS",
      sharesLabel: "SHARES"
    },
    reviewer: {
      dashboard: "Reviewer Dashboard",
      activeStudies: "Active Studies",
      currentReviews: "Current Reviews",
      incomingStudies: "Incoming Studies",
      underReview: "Under Review",
      waitingReview: "Waiting for Review",
      revisionRequired: "Waiting for Revision",
      startReview: "Start Review",
      continueReview: "Continue Review",
      manageReviews: "Manage Study Reviews",
      reviewStudy: "Review Study",
      noActiveStudies: "No studies are currently being reviewed.",
      noIncomingStudies: "No studies are waiting for review.",
      studyBeingHandled: "Studies currently assigned to you for review.",
      newStudies: "New studies received",
      studiesYouReview: "Studies you are currently reviewing",
      approve: "Approve",
      requestRevision: "Request Revision",
      reject: "Reject",
      approvalFlow: "Approval Flow",
      reviewerOnly: "Reviewer only",
      reviewerDirector: "Reviewer + Director",
      notePlaceholder: "Write reviewer notes...",
      notePlaceholder: "Write reviewer notes..."
    },
    director: {
      dashboard: "Director Dashboard",
      review: "Study Review",
      reviewStudies: "Studies Awaiting Review",
      incomingStudies: "Incoming Studies",
      directorReview: "Director Review",
      waitingReview: "Waiting for Review",
      revisionRequired: "Waiting for Revision",
      startReview: "Start Review",
      continueReview: "Continue Review",
      manageReviews: "Manage Study Reviews",
      noStudies: "No studies are waiting for review.",
      approve: "Approve & Publish",
      requestRevision: "Request Revision",
      reject: "Reject",
      notePlaceholder: "Write Director notes...",
      notePlaceholder: "Write Director notes..."
    },
    admin: {
      dashboard: "Admin Dashboard",
      management: "Platform Management",
      overview: "Overview",
      performance: "Performance",
      analytics: "Analytics",
      platformActivity: "Platform Activity",
      studies: "Studies",
      studyManagement: "Study Management",
      allStudies: "All Studies",
      manageStudies: "Monitor all studies and manage deletion requests from researchers.",
      noStudies: "No studies yet.",
      studyNotFound: "Study not found.",
      viewStudy: "View Study",
      users: "Users",
      userManagement: "User Management",
      manageUsers: "Manage researcher, reviewer, director, and administrator accounts.",
      noUsers: "No users yet.",
      categories: "Categories",
      categoryManagement: "Category Management",
      manageCategories: "Manage categories used to organize studies.",
      noCategories: "No categories yet.",
      deletionRequest: "Deletion Request",
      deletionRequests: "Deletion Requests",
      pendingDeletion: "Pending deletion requests.",
      approveDeletion: "Approve & Delete",
      rejectDeletion: "Reject Request",
      rejectRequest: "Reject Request",
      rejectionReason: "Explain the reason for rejecting this deletion request.",
      confirmDeletion: "Approve Deletion?",
      deleteConfirmation: "Are you sure you want to delete this study?",
      published: "Published",
      underReview: "Under Review",
      waitingReviewer: "Waiting for Reviewer",
      directorReview: "Director Review",
      totalUsers: "Total Users",
      totalStudies: "Total Studies",
      totalViews: "Total Views",
      totalLikes: "Total Likes",
      totalComments: "Total Comments",
      totalShares: "Total Shares",
      uniqueVisitors: "Unique Visitors",
      studyViews: "Study Views",
      traffic: "Traffic",
      categoryDistribution: "Category Distribution",
      workflowDistribution: "Workflow Distribution",
      popularStudies: "Popular Studies",
      recentActivity: "Activity in the Last 7 Days",
      engagement: "Based on engagement",
      categoryNamePlaceholder: "Example: Web Scraping",
      categoryDescriptionPlaceholder: "Short category description",
      searchStudyPlaceholder: "Search study title...",
      rejectionReasonPlaceholder: "Write rejection reason...",
      searchUserPlaceholder: "Search name or email...",
      passwordMinimum: "Password must be at least 8 characters",
      waitingReview: "Waiting for Review"
    },
    editor: {
      primary: "PRIMARY",
      embed: "EMBED",
      text: "Text",
      textDescription: "Write a regular paragraph",
      heading: "Heading",
      headingDescription: "Main section heading",
      subheading: "Subheading",
      subheadingDescription: "Section subtitle",
      image: "Image",
      imageDescription: "Upload or add an image",
      gallery: "Gallery",
      galleryDescription: "Create a multi-image gallery",
      divider: "Divider",
      dividerDescription: "Add a divider line",
      quote: "Quote",
      quoteDescription: "Add a quotation",
      callout: "Callout",
      calloutDescription: "Highlight an information box",
      video: "Video",
      videoDescription: "Add a video from a URL",
      pdf: "File / PDF",
      pdfDescription: "Upload a PDF document",
      button: "Button",
      buttonDescription: "Add a link button",
      code: "Code",
      codeDescription: "Add a code block",
      youtube: "YouTube",
      youtubeDescription: "Embed YouTube video",
      github: "GitHub",
      githubDescription: "Display GitHub repository",
      gitlab: "GitLab",
      gitlabDescription: "Display GitLab repository",
      vimeo: "Vimeo",
      vimeoDescription: "Embed Vimeo video",
      embed: "Embed",
      embedDescription: "Enter embed URL",
      titlePlaceholder: "Enter study title...",
      keywordPlaceholder: "Type a keyword and press Enter...",
      summaryPlaceholder: "Briefly describe the study...",
      contentPlaceholder: "Start writing your study... Type / to add a block.",
      maxKeywords: "Maximum 7 keywords.",
      maxGallery: "Maximum 8 images per gallery.",
      maxImageSize: "Each image must be no larger than 4 MB.",
      maxPdfSize: "Maximum PDF size is 10 MB.",
      selectedPdf: "PDF Document",
      openFull: "Open full",
      studyVideo: "Study video",
      previewCover: "Cover preview",
      addCallout: "Add Callout",
      addVideo: "Add Video",
      addButton: "Add Button",
      addBlock: "Add Block",
      uploadPdfOnly: "The selected file must be a PDF.",
      uploadImageError: "Failed to upload image.",
      uploadGalleryError: "Failed to upload gallery.",
      embedStudy: "Study Embed",
      calloutTitle: "Callout Title",
      calloutContent: "Callout Content",
      buttonText: "Button Text",
      targetUrl: "Target URL",
      imageDescription: "Image Description",
      noContent: "No study content yet.",
      calloutPlaceholder: "Write the information you want to highlight...",
      seeMore: "See More",
      imageDescriptionPlaceholder: "Describe the image...",
      closePreview: "Close preview",
      calloutTitlePlaceholder: "Enter callout title...",
      buttonTextPlaceholder: "Example: See More",
      type: "Type",
      warning: "Warning",
      success: "Success",
      important: "Important",
      youtubeUrl: "YouTube URL",
      vimeoUrl: "Vimeo URL",
      embedUrl: "Embed URL",
      videoUrl: "Video URL",
      githubRepositoryUrl: "GitHub Repository URL",
      gitlabRepositoryUrl: "GitLab Repository URL",
      enterGithubRepository: "Enter GitHub repository URL.",
      enterGitlabRepository: "Enter GitLab repository URL.",
      enterEmbedUrl: "Enter the URL you want to embed into the study.",
      editor: "EDITOR",
      preview: "Preview",
      typeCommand: "Type / for command",
      urlRequired: "URL cannot be empty.",
      imageSizeError: "Maximum image size is 4 MB.",
      imageUploadError: "Failed to upload image.",
      imageUploadFailed: "Image upload failed.",
      galleryMax: "Maximum 8 images per gallery.",
      galleryImageMaxSize: "Each image must be no larger than 4 MB.",
      galleryUploadError: "Failed to upload gallery.",
      galleryUploadFailed: "Gallery upload failed."
    },
    modal: {
      confirmation: "Confirmation",
      continue: "Yes, Continue",
      cancel: "Cancel",
      close: "Close",
      inputInformation: "Enter Information",
      input: "Input",
      save: "Save"
    },
    toast: {
      success: "Success",
      error: "An Error Occurred",
      warning: "Warning",
      close: "Close"
    }
  }
};
const LanguageContext = createContext(null);
function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    if (typeof window === "undefined") {
      return "id";
    }
    return window.localStorage.getItem("language") || "id";
  });
  useEffect(() => {
    window.localStorage.setItem("language", language);
  }, [language]);
  const t = translations[language];
  return /* @__PURE__ */ jsx(
    LanguageContext.Provider,
    {
      value: {
        language,
        setLanguage,
        t
      },
      children
    }
  );
}
function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error(
      "useLanguage harus digunakan di dalam LanguageProvider"
    );
  }
  return context;
}
createServer(
  (page) => createInertiaApp({
    page,
    render: renderToString,
    resolve: (name) => resolvePageComponent(
      `./Pages/${name}.jsx`,
      /* @__PURE__ */ Object.assign({ "./Pages/Admin/Categories/Index.jsx": () => import("./assets/Index-DmBBiSm7.js"), "./Pages/Admin/Dashboard.jsx": () => import("./assets/Dashboard-BpVX3WXB.js"), "./Pages/Admin/Studies/Index.jsx": () => import("./assets/Index-X-1OHIms.js"), "./Pages/Admin/Users/Index.jsx": () => import("./assets/Index-B19mbp1h.js"), "./Pages/Auth/ConfirmPassword.jsx": () => import("./assets/ConfirmPassword-BkTZMjFS.js"), "./Pages/Auth/ForgotPassword.jsx": () => import("./assets/ForgotPassword-DoYx0KMH.js"), "./Pages/Auth/Login.jsx": () => import("./assets/Login-1HCF_szb.js"), "./Pages/Auth/Register.jsx": () => import("./assets/Register-D3onwed_.js"), "./Pages/Auth/ResetPassword.jsx": () => import("./assets/ResetPassword-BcD2WM9y.js"), "./Pages/Auth/VerifyEmail.jsx": () => import("./assets/VerifyEmail-NJltJXZO.js"), "./Pages/Director/Analytics.jsx": () => import("./assets/Analytics-zG-a5-7E.js"), "./Pages/Director/Dashboard.jsx": () => import("./assets/Dashboard-i9_QcX8s.js"), "./Pages/Director/StudyReview.jsx": () => import("./assets/StudyReview-CjySB29o.js"), "./Pages/Profile/Edit.jsx": () => import("./assets/Edit-CxNxd6C8.js"), "./Pages/Public/Home.jsx": () => import("./assets/Home-sJhmfiTn.js"), "./Pages/Public/Studies.jsx": () => import("./assets/Studies-DGB6zadF.js"), "./Pages/Public/StudyDetail.jsx": () => import("./assets/StudyDetail-gzUkO-vP.js"), "./Pages/Reviewer/ActiveStudies.jsx": () => import("./assets/ActiveStudies-CpLBAmL2.js"), "./Pages/Reviewer/Analytics.jsx": () => import("./assets/Analytics-DC_lDNNJ.js"), "./Pages/Reviewer/Dashboard.jsx": () => import("./assets/Dashboard-BkOV0rZ6.js"), "./Pages/Reviewer/StudyReview.jsx": () => import("./assets/StudyReview-5ogGzAdz.js"), "./Pages/User/Analytics.jsx": () => import("./assets/Analytics-DnpI67bm.js"), "./Pages/User/Dashboard.jsx": () => import("./assets/Dashboard-B_pS_bkS.js"), "./Pages/User/Studies/Create.jsx": () => import("./assets/Create-DcbKwvnG.js"), "./Pages/User/Studies/Edit.jsx": () => import("./assets/Edit-DCAy4yj2.js") })
    ),
    setup: ({ App, props }) => /* @__PURE__ */ jsx(LanguageProvider, { children: /* @__PURE__ */ jsx(App, { ...props }) })
  })
);
export {
  useLanguage as u
};
